# Generated by Django 3.0.2 on 2020-01-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='berat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buku',
            name='diskon',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='buku',
            name='hal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buku',
            name='harganormal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='buku',
            name='photo1',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='buku',
            name='photo2',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
