# Generated by Django 3.0.2 on 2020-01-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_auto_20200124_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='penulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buku.Penulis'),
        ),
    ]
