# Generated by Django 3.0.2 on 2020-01-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_buku_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='diskon',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buku',
            name='harganormal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
